production:
  delivery_method: :smtp
  smtp_settings:
    tls: true
    address: "smtp.sendgrid.net"
    enable_starttls_auto: true
    port: 587
    authentication: :plain
    domain: "heroku.com"
    user_name: "stoneig"
    password: "StonePa55"
